#############################################################################
# Makefile for building: access_control
# Generated by qmake (1.07a) (Qt 3.3.8b) on: Sun Jun  3 08:05:27 2012
# Project:  access_control.pro
# Template: app
# Command: $(QMAKE) -o Makefile access_control.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -g -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
CXXFLAGS = -pipe -g -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/share/qt3/mkspecs/default -I. -I/usr/include/qt3 -I.ui/ -I. -I.moc/
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L/usr/share/qt3/lib -L/usr/X11R6/lib -lqt-mt -lXext -lX11 -lm -lpthread
AR       = ar cqs
RANLIB   = 
MOC      = /usr/share/qt3/bin/moc
UIC      = /usr/share/qt3/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = .obj/

####### Files

HEADERS = data/common.h
SOURCES = main.cpp \
		data/common.cpp
OBJECTS = .obj/main.o \
		.obj/common.o \
		.obj/mainwnd.o
FORMS = mainwnd.ui
UICDECLS = .ui/mainwnd.h
UICIMPLS = .ui/mainwnd.cpp
SRCMOC   = .moc/moc_mainwnd.cpp
OBJMOC = .obj/moc_mainwnd.o
DIST	   = access_control.pro
QMAKE_TARGET = access_control
DESTDIR  = 
TARGET   = access_control

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: access_control.pro  /usr/share/qt3/mkspecs/default/qmake.conf /usr/share/qt3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile access_control.pro
qmake: 
	@$(QMAKE) -o Makefile access_control.pro

dist: 
	@mkdir -p .obj/access_control && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .obj/access_control/ && $(COPY_FILE) --parents mainwnd.ui.h .obj/access_control/ && ( cd `dirname .obj/access_control` && $(TAR) access_control.tar access_control && $(GZIP) access_control.tar ) && $(MOVE) `dirname .obj/access_control`/access_control.tar.gz . && $(DEL_FILE) -r .obj/access_control

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:
	-$(DEL_FILE) $(UICIMPLS) $(UICDECLS)

yaccclean:
lexclean:
clean: mocclean uiclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

.obj/main.o: main.cpp .ui/mainwnd.h \
		data/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o main.cpp

.obj/common.o: data/common.cpp data/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/common.o data/common.cpp

.ui/mainwnd.h: mainwnd.ui data/common.h
	$(UIC) mainwnd.ui -o .ui/mainwnd.h

.ui/mainwnd.cpp: .ui/mainwnd.h mainwnd.ui mainwnd.ui.h data/common.h
	$(UIC) mainwnd.ui -i mainwnd.h -o .ui/mainwnd.cpp

.obj/mainwnd.o: .ui/mainwnd.cpp mainwnd.ui.h \
		.ui/mainwnd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/mainwnd.o .ui/mainwnd.cpp

.obj/moc_mainwnd.o: .moc/moc_mainwnd.cpp  .ui/mainwnd.h data/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_mainwnd.o .moc/moc_mainwnd.cpp

.moc/moc_mainwnd.cpp: $(MOC) .ui/mainwnd.h
	$(MOC) .ui/mainwnd.h -o .moc/moc_mainwnd.cpp

####### Install

install:  

uninstall:  

